from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)

from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors
from datetime import datetime


def generate_basic_report(
    file_path,
    rows,
    columns,
    missing_values,
    duplicate_rows,
    numeric_columns,
    categorical_columns
):

    styles = getSampleStyleSheet()

    document = SimpleDocTemplate(file_path)

    story = []

    # ==========================================================
    # TITLE
    # ==========================================================

    story.append(
        Paragraph(
            "📊 DataPilot AI",
            styles["Title"]
        )
    )

    story.append(
        Paragraph(
            "Business Intelligence Report",
            styles["Heading2"]
        )
    )

    story.append(Spacer(1, 10))

    current_time = datetime.now().strftime("%d %B %Y, %I:%M %p")

    story.append(
        Paragraph(
            f"<b>Generated On:</b> {current_time}",
            styles["BodyText"]
        )
    )

    story.append(Spacer(1, 20))

    # ==========================================================
    # DATASET SUMMARY
    # ==========================================================

    story.append(
        Paragraph(
            "<b>Dataset Summary</b>",
            styles["Heading2"]
        )
    )

    story.append(Spacer(1, 10))

    table_data = [

        ["Metric", "Value"],

        ["Rows", rows],

        ["Columns", columns],

        ["Missing Values", missing_values],

        ["Duplicate Rows", duplicate_rows]

    ]

    table = Table(
        table_data,
        colWidths=[250, 120]
    )

    table.setStyle(

        TableStyle([

            ("BACKGROUND", (0, 0), (-1, 0), colors.darkblue),

            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),

            ("ALIGN", (0, 0), (-1, -1), "CENTER"),

            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),

            ("BOTTOMPADDING", (0, 0), (-1, 0), 12),

            ("GRID", (0, 0), (-1, -1), 1, colors.black),

            ("BACKGROUND", (0, 1), (-1, -1), colors.beige)

        ])

    )

    story.append(table)

    story.append(Spacer(1, 30))

    story.append(Spacer(1, 20))

    story.append(
        Paragraph(
            "<b>Dataset Statistics</b>",
            styles["Heading2"]
        )
    )

    story.append(Spacer(1, 10))

    statistics_data = [

        ["Statistic", "Value"],

        ["Numeric Columns", numeric_columns],

        ["Categorical Columns", categorical_columns],

        ["Missing Values", missing_values],

        ["Duplicate Rows", duplicate_rows]

    ]

    statistics_table = Table(
        statistics_data,
        colWidths=[250, 120]
    )

    statistics_table.setStyle(

        TableStyle([

            ("BACKGROUND", (0, 0), (-1, 0), colors.darkgreen),

            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),

            ("GRID", (0, 0), (-1, -1), 1, colors.black),

            ("BACKGROUND", (0, 1), (-1, -1), colors.whitesmoke),

            ("ALIGN", (0, 0), (-1, -1), "CENTER"),

            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),

            ("BOTTOMPADDING", (0, 0), (-1, 0), 12)

        ])

    )

    story.append(statistics_table)

    # ==========================================================
    # FOOTER
    # ==========================================================

    story.append(
        Paragraph(
            "<b>Generated by DataPilot AI</b>",
            styles["Heading3"]
        )
    )

    story.append(
        Paragraph(
            "AI-Powered Business Intelligence Platform",
            styles["Italic"]
        )
    )

    # Build PDF
    document.build(story)


# ==========================================================
# TEST
# ==========================================================

if __name__ == "__main__":

    generate_basic_report(
        "sample_report.pdf",
        102,
        13,
        18,
        2,
        8,
        5
    )

    print("PDF Created Successfully!")